### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by n8o** [jjustman/libatsc3#132]
I was wondering if you could provide a list of hardware that you currently recommend. For Modulation, receiver, players. etc..

**Comment by jjustman** [comment]
For modulation, I would recommend either:

Single channel modulation: https://www.dektec.com/products/USB/DTU-315/
Up to 8 channels using libatsc3+dtapi tools: https://www.dektec.com/products/PCIe/DTA-2115B/

Receiver Hardware: 
Airwavz.tv Redzone Receiver Plus (RZR-1400): https://redzonereceiver.tv/product/redzone-receiver-plus

Otherwise, there isn't that many ATSC 3.0 dongles that are commercially available (I can advise privately for other engineering samples)

Consumer Receiver Devices:
HDHomeRun: https://www.silicondust.com/
ZapperBox: https://zapperbox.com/
